### ISSUE TITLE
undefined symbol: aio_read

### ISSUE THREAD

**Issue by PWZER** [tensorflow/recommenders-addons#187]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow version and how it was installed (source or binary): v2.5.1, source
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): source
- Python version: 3.8.10
- Is GPU used? (yes/no): no

**Describe the bug**

```python
root@7c22b3f4c4a6:/workspace# python -c "import tensorflow_recommenders_addons as tfra"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/__init__.py", line 30, in <module>
    from tensorflow_recommenders_addons import dynamic_embedding
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/__init__.py", line 53, in <module>
    from tensorflow_recommenders_addons.dynamic_embedding.python.ops.redis_table_ops import (
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py", line 37, in <module>
    redis_table_ops = LazySO("dynamic_embedding/core/_redis_table_ops.so").ops
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/utils/resource_loader.py", line 102, in ops
    self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/core/_redis_table_ops.so: undefined symbol: aio_read
```

**Comment by PWZER** [comment]
Build with the following command is work

```bash
bazel build --linkopt='-lrt' --enable_runfiles build_pip_pkg
```

**Comment by rhdong** [comment]
> Build with the following command is work
> 
> ```shell
> bazel build --linkopt='-lrt' --enable_runfiles build_pip_pkg
> ```

@PWZER Thank you !
and Hi @MoFHeka , do we make any mistake in Redis Build file?
