### ISSUE TITLE
how can i use RestrictPolicy in estimator to eliminate features in variable follow the `oldest-out-first` rule?

### ISSUE THREAD

**Issue by tsaichasel** [tensorflow/recommenders-addons#190]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.6 LTS
- TensorFlow version and how it was installed (source or binary):2.5.1
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary):source
- Python version:Python 3.6.9
- Is GPU used? (yes/no):no

**Describe the bug**

When i use RestrictPolicy in estimator, how can i use `apply_update` and `apply_restriction` to eliminate features in variable follow the `oldest-out-first` rule?

`user_embeddings` and `movie_embeddings` were created in model_fn, how can i get these two embedding weight and 
apply `apply_restriction`?

i try to use `get_variable` to get  `user_embeddings` or `movie_embeddings` in `SessionRunHook`, but get **ValueError: Variable user_dynamic_embeddings already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?**

anyone can give me some suggest?

**Code to reproduce the issue**
```python
import json
import os

import tensorflow as tf
from tensorflow.keras.layers import Dense

import tensorflow_datasets as tfds
import tensorflow_recommenders_addons as tfra

from absl import app
from absl import flags

flags.DEFINE_string('model_dir', "./incrm_ckpt", 'export_dir')
flags.DEFINE_string('export_dir', "./export_dir", 'export_dir')
flags.DEFINE_string('mode', "train", 'train or export')

FLAGS = flags.FLAGS

try:
    _SessionRunHook = tf.estimator.SessionRunHook
except AttributeError:
    try:
        _SessionRunHook = tf.train.SessionRunHook
    except AttributeError:
        _SessionRunHook = None

if _SessionRunHook is not None:
  class UpdateEmbeddingHook(_SessionRunHook):
    def begin(self):
      print(" === begin")
      
    def after_run(self, run_context, run_values):
      print(" === after_run")
      self.user_embeddings = tfra.dynamic_embedding.get_variable(name="user_dynamic_embeddings")
      print(self.user_embeddings)
      keys, tstp = run_context.session.run(self.user_embeddings.restrict_policy.status.export())
      k, v = run_context.session.run(self.user_embeddings.export())
      print(' === keys   :{}\n === tstp  :{}\n === values :\n{}'.format(keys, tstp, v))

def input_fn():
  ratings = tfds.load("movielens/100k-ratings", split="train")
  ratings = ratings.map(
      lambda x: {
          "movie_id": tf.strings.to_number(x["movie_id"], tf.int64),
          "user_id": tf.strings.to_number(x["user_id"], tf.int64),
          "user_rating": x["user_rating"]
      })
  shuffled = ratings.shuffle(1_000_000, seed=2021, reshuffle_each_iteration=False)
  dataset = shuffled.batch(256)
  return dataset

def model_fn(features, labels, mode, params):
  embedding_size = 32
  movie_id = features["movie_id"]
  user_id = features["user_id"]
  rating = features["user_rating"]

  is_training = (mode == tf.estimator.ModeKeys.TRAIN)

  if is_training:
    initializer = tf.keras.initializers.RandomNormal(-1, 1)
  else:
    initializer = tf.keras.initializers.Zeros()

  # from tensorflow.python.ops import variable_scope
  # with variable_scope.variable_scope("test", reuse=variable_scope.AUTO_REUSE):
  #   # Create embedding variable by `tfra.dynamic_embedding` API.
  user_embeddings = tfra.dynamic_embedding.get_variable(
      name="user_dynamic_embeddings",
      dim=embedding_size,
      initializer=initializer,
      trainable=True,
      restrict_policy=tfra.dynamic_embedding.TimestampRestrictPolicy)
  movie_embeddings = tfra.dynamic_embedding.get_variable(
      name="moive_dynamic_embeddings",
      dim=embedding_size,
      initializer=initializer,
      trainable=True,
      restrict_policy=tfra.dynamic_embedding.TimestampRestrictPolicy)

  user_id_val, user_id_idx = tf.unique(tf.concat(user_id, axis=0))
  user_id_weights, user_id_trainable_wrapper = tfra.dynamic_embedding.embedding_lookup(
      params=user_embeddings,
      ids=user_id_val,
      name="user-id-weights",
      return_trainable=True)
  user_id_weights = tf.gather(user_id_weights, user_id_idx)

  movie_id_val, movie_id_idx = tf.unique(tf.concat(movie_id, axis=0))
  movie_id_weights, movie_id_trainable_wrapper = tfra.dynamic_embedding.embedding_lookup(
      params=movie_embeddings,
      ids=movie_id_val,
      name="movie-id-weights",
      return_trainable=True)
  movie_id_weights = tf.gather(movie_id_weights, movie_id_idx)

  embeddings = tf.concat([user_id_weights, movie_id_weights], axis=1)
  d0 = Dense(256,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
  d1 = Dense(64,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
  d2 = Dense(1,
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
  dnn = d0(embeddings)
  dnn = d1(dnn)
  dnn = d2(dnn)
  out = tf.reshape(dnn, shape=[-1])
  loss = tf.keras.losses.MeanSquaredError()(rating, out)
  predictions = {"out": out}

  if mode == tf.estimator.ModeKeys.EVAL:
    eval_metric_ops = {}
    return tf.estimator.EstimatorSpec(mode=mode,
                                      loss=loss,
                                      eval_metric_ops=eval_metric_ops)

  if mode == tf.estimator.ModeKeys.TRAIN:
    optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.001)
    optimizer = tfra.dynamic_embedding.DynamicEmbeddingOptimizer(optimizer)
    train_op = optimizer.minimize(loss, global_step=tf.compat.v1.train.get_or_create_global_step())
    return tf.estimator.EstimatorSpec(mode=mode,
                                      predictions=predictions,
                                      loss=loss,
                                      train_op=train_op)

  if mode == tf.estimator.ModeKeys.PREDICT:
    predictions_for_net = {"out": out}
    export_outputs = {
        "predict_export_outputs":
            tf.estimator.export.PredictOutput(outputs=predictions_for_net)
    }
    return tf.estimator.EstimatorSpec(mode,
                                      predictions=predictions_for_net,
                                      export_outputs=export_outputs)


def train(model_dir):
  model_config = tf.estimator.RunConfig(log_step_count_steps=100,
                                        save_summary_steps=100,
                                        save_checkpoints_steps=100,
                                        save_checkpoints_secs=None,
                                        keep_checkpoint_max=2)

  estimator = tf.estimator.Estimator(model_fn=model_fn,
                                     model_dir=model_dir,
                                     config=model_config)

  train_spec = tf.estimator.TrainSpec(input_fn=input_fn)

  eval_spec = tf.estimator.EvalSpec(input_fn=input_fn)

  # tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  updateEmbeddingHook = UpdateEmbeddingHook()
  estimator.train(input_fn=input_fn, hooks=[updateEmbeddingHook])
    


def serving_input_receiver_dense_fn():
  input_spec = {
      "movie_id": tf.constant([1], tf.int64),
      "user_id": tf.constant([1], tf.int64),
      "user_rating": tf.constant([1.0], tf.float32)
  }
  return tf.estimator.export.build_raw_serving_input_receiver_fn(input_spec)


def export_for_serving(model_dir, export_dir):
  model_config = tf.estimator.RunConfig(log_step_count_steps=100,
                                        save_summary_steps=100,
                                        save_checkpoints_steps=100,
                                        save_checkpoints_secs=None)

  estimator = tf.estimator.Estimator(model_fn=model_fn,
                                     model_dir=model_dir,
                                     config=model_config)

  estimator.export_saved_model(export_dir, serving_input_receiver_dense_fn())

def main(argv):
  if FLAGS.mode == "train":
    train(FLAGS.model_dir)
  if FLAGS.mode == "serving" and task_name == "chief" and int(task_idx) == 0:
    tfra.dynamic_embedding.enable_inference_mode()
    export_for_serving(FLAGS.model_dir, FLAGS.export_dir)

if __name__ == "__main__":
  app.run(main)
```

**Other info / logs**

```
I1125 02:36:43.168426 140397124024128 basic_session_run_hooks.py:626] Calling checkpoint listeners after saving checkpoint 0...
2021-11-25 02:36:43.306006: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
 === after_run
Traceback (most recent call last):
  File "movielens-100k-estimator_sgl.py", line 198, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "movielens-100k-estimator_sgl.py", line 191, in main
    train(FLAGS.model_dir)
  File "movielens-100k-estimator_sgl.py", line 163, in train
    estimator.train(input_fn=input_fn, hooks=[updateEmbeddingHook])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1514, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 779, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1284, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1385, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1370, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1451, in run
    run_metadata=run_metadata))
  File "movielens-100k-estimator_sgl.py", line 40, in after_run
    self.user_embeddings = tfra.dynamic_embedding.get_variable(name="user_dynamic_embeddings")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py", line 729, in get_variable
    raise ValueError(err_msg)
ValueError: Variable user_dynamic_embeddings already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?
```

**Comment by rhdong** [comment]
@TsaiChasel15 Try to call `tf.compat.v1.disable_v2_behavior()` at the begin, using Graph mode, thank you!

**Comment by MoFHeka** [comment]
Please disable_v2_behavior when using Estimator.
Has the problem been solved? May I close this issue now?
