### ISSUE TITLE
Fail to load saved model 

### ISSUE THREAD

**Issue by Lihengwannafly** [tensorflow/recommenders-addons#220]
**System information**
- TensorFlow version and how it was installed (source or binary): 2.5.1
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): source
- Python version: 3.8
- Is GPU used? (yes/no): yes

**Describe the bug**
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 337, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 302, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 454, in load
    saver, _ = self.load_graph(sess.graph, tags, import_scope,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 384, in load_graph
    return tf_saver._import_meta_graph_with_return_elements(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/saver.py", line 1486, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/meta_graph.py", line 887, in import_scoped_meta_graph_with_return_elements
    col_op = graph.as_graph_element(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 3755, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 3814, in _as_graph_element_locked
    raise KeyError("The name %s refers to an Operation not in the "
KeyError: "The name 'feature_processing/zis_holiday' refers to an Operation not in the graph."
```

**Code to reproduce the issue**
```
import tensorflow as tf
tf.compat.v1.disable_v2_behavior()
import tensorflow_recommenders_addons as tfra

with tf.compat.v1.Session() as session:
    tf.compat.v1.saved_model.load(session, [tf.saved_model.SERVING], "./saved_model/20220222_082154")
```

**Comment by rhdong** [comment]
Hi @Lihengwannafly ,thank you for feedback, could you provide the reproduce script and model files? thank you.
Hi @Lifann , maybe you already resolve this?

**Comment by Lihengwannafly** [comment]
```
    outputs, trainable_variable = de.embedding_lookup_sparse(params=embedding_variable,
                                                             sp_ids=key,
                                                             sp_weights=value,
                                                             combiner=combiner,
                                                             name=embedding_name + "_dynamic_sparse_lookup",
                                                             return_trainable=True)
    if 'collection' in config.keys():
        tf.compat.v1.add_to_collection(config['collection'], trainable_variable)
```

If add embedding_variable to collection, the issus will reproduce.

**Comment by Lifann** [comment]
trainable_varaible returned from embedding_lookup series API is a temporary buffer for current device. It's will be automatically added to local variable. No need to add it to other collection. If need to access the trainables globally, I think you could just use a python context.

**Comment by MoFHeka** [comment]
The issue seems to have been fixed, so close the issue for now. And you can reopen it at any time if needed. @Lihengwannafly
