### ISSUE TITLE
[BUG] Colocation error when place Variable on CPU and TrainableWrapper on GPU

### ISSUE THREAD

**Issue by Lifann** [tensorflow/recommenders-addons#232]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Centos 7
- TensorFlow version and how it was installed (source or binary): 2.5.1 from binary
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): tensorflow-recommenders-addons-gpu==0.4.0
- Python version: 3.8.7
- Is GPU used? (yes/no): yes

**Describe the bug**

Since the GPU memory is very limited, so I tried to place the dynamice_embedding.Variable on host memory, and use the TrainableWrapper as a temporary buffer to prefetch the lookup result to GPU. In forward and backward computation, everything works fine. But when I ran `optimizer.apply_grdianet` on the GPU TrainableWrapper, I got following errors:
```bash
Traceback (most recent call last):
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot colocate nodes {{colocation_node embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape}} and {{colocation_node random_uniform}}: Cannot merge devices with incompatible types: '/device:GPU:0' and '/device:CPU:0'
         [[{{node embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape}}]]

During handling of the above exception, another exception occurred:
```

**Code to reproduce the issue**

```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

import tensorflow as tf
from tensorflow_recommenders_addons import dynamic_embedding as de

tf.compat.v1.disable_v2_behavior()


def test_reproduce_issue():
  batch_size = 128
  seq_len = 1000
  global_vocab_size = 10_0000
  embedding_size = 64
  val_inititializer = tf.compat.v1.random_normal_initializer(dtype=tf.float32)

  embedding_var = de.get_variable(
      'tfra_var',
      dim=embedding_size,
      devices=['/CPU:0'],
      key_dtype=tf.int64,
      value_dtype=tf.float32,
      initializer=val_inititializer)

  initializer = tf.keras.initializers.RandomUniform(0, global_vocab_size)
  data = initializer((batch_size, seq_len,), dtype=tf.int64)

  lookup_result, trainable = de.embedding_lookup(embedding_var, data, return_trainable=True)

  optimizer = tf.compat.v1.train.AdamOptimizer(1E-3)
  optimizer = de.DynamicEmbeddingOptimizer(optimizer)

  loss = tf.reduce_sum(lookup_result)
  with tf.device('/GPU:0'):
    grads_and_vars = optimizer.compute_gradients(loss, var_list=[trainable])  # this is ok
    run_op = optimizer.apply_gradients(grads_and_vars)  # this will fail.

  config = tf.compat.v1.ConfigProto()
  config.gpu_options.allow_growth = True

  with tf.compat.v1.Session(config=config) as sess:
      sess.run(tf.compat.v1.global_variables_initializer())
      sess.run(run_op)

if __name__ == '__main__':
  test_reproduce_issue()
```

**Other info / logs**
```bash
Call initializer instance with the dtype argument instead of passing it to the constructor
2022-03-31 11:50:43.638876: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-31 11:50:43.640646: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-03-31 11:50:43.651276: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-31 11:50:43.653750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:09.0 name: GRID T4-8C computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 298.08GiB/s
2022-03-31 11:50:43.653875: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-03-31 11:50:43.656486: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-03-31 11:50:43.656563: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2022-03-31 11:50:43.657797: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2022-03-31 11:50:43.658093: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2022-03-31 11:50:43.660878: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2022-03-31 11:50:43.661549: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2022-03-31 11:50:43.661706: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2022-03-31 11:50:43.661808: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-31 11:50:43.665003: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-31 11:50:43.667348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-03-31 11:50:44.741278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-03-31 11:50:44.741323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2022-03-31 11:50:44.741336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2022-03-31 11:50:44.741551: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-31 11:50:44.742612: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-31 11:50:44.743506: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-31 11:50:44.744465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5717 MB memory) -> physical GPU (device: 0, name: GRID T4-8C, pci bus id: 0000:00:09.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot colocate nodes {{colocation_node embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape}} and {{colocation_node random_uniform}}: Cannot merge devices with incompatible types: '/device:GPU:0' and '/device:CPU:0'
         [[{{node embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark_between_curry_superion.py", line 46, in <module>
    test_reproduce_issue()
  File "benchmark_between_curry_superion.py", line 42, in test_reproduce_issue
    sess.run(tf.compat.v1.global_variables_initializer())
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot colocate nodes node embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape (defined at /data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py:529) placed on device Device assignments active during op 'embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape' creation:
  with tf.device(/CPU:0): </data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py:567>
  with tf.device(): </data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py:294>  and node random_uniform (defined at benchmark_between_curry_superion.py:26) placed on device No device assignments were active during op 'random_uniform' creation. : Cannot merge devices with incompatible types: '/device:GPU:0' and '/device:CPU:0'
         [[node embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape (defined at /data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py:529) ]]Additional information about colocations:Node-device colocations active during op 'embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape' creation:
  with tf.colocate_with(random_uniform): </data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py:586>
Device assignments active during op 'embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape' creation:
  with tf.device(/CPU:0): </data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py:567>
  with tf.device(): </data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py:294>
No node-device colocations were active during op 'random_uniform' creation.
No device assignments were active during op 'random_uniform' creation.

Original stack trace for 'embedding_lookup/embedding_lookup/_anonymous_trainable_store_key/Read/Reshape/shape':
  File "benchmark_between_curry_superion.py", line 46, in <module>
    test_reproduce_issue()
  File "benchmark_between_curry_superion.py", line 28, in test_reproduce_issue
    lookup_result, trainable = de.embedding_lookup(embedding_var, data, return_trainable=True)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py", line 587, in embedding_lookup
    trainable_ = _create_or_get_trainable(name)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py", line 562, in _create_or_get_trainable
    wrapper = de.TrainableWrapper(params,
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py", line 91, in __init__
    super(TrainableWrapper, self).__init__(*args, **kwargs)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1584, in __init__
    self._init_from_args(
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py", line 298, in _init_from_args
    self.prefetch_values(),
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py", line 99, in prefetch_values
    self.prefetch_values_op = self.transform(self.params.lookup(self.ids))
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py", line 568, in lookup
    dynamic_default_values = self._create_default_values_by_initializer(
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py", line 529, in _create_default_values_by_initializer
    keys_shape = array_ops.shape(array_ops.reshape(keys, [-1]))
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8397, in reshape
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 497, in _apply_op_helper
    inferred = ops.convert_to_tensor(
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 286, in _constant_impl
    const_tensor = g._create_op_internal(  # pylint: disable=protected-access
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "/data/env/py3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

```

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Lifann** [comment]
Solved by placing initializer on CPU either
