### ISSUE TITLE
AttributeError: 'GlorotUniform' object has no attribute '_random_generator'

### ISSUE THREAD

**Issue by PWZER** [tensorflow/recommenders-addons#236]
## Reproduce Code

```python
import tensorflow as tf

tf.compat.v1.disable_v2_behavior()  # remove this row is work

from tensorflow_recommenders_addons import dynamic_embedding as de


with tf.compat.v1.Session() as sess:
    inputs = tf.compat.v1.placeholder(tf.float32, shape=(1, 3))
    output = tf.compat.v1.layers.dense(inputs, units=8)

    sess.run(tf.compat.v1.global_variables_initializer())

    res = sess.run(output, feed_dict={inputs: [[1.0, 2.0, 3.0]]})
    print(res.tolist())
```

## Exception

```bash
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    output = tf.compat.v1.layers.dense(inputs, units=8)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/legacy_tf_layers/core.py", line 188, in dense
    return layer.apply(inputs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1695, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 561, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 763, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2084, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/layers/core.py", line 1191, in build
    self.kernel = self.add_weight(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 454, in add_weight
    variable = super(Layer, self).add_weight(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 441, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/tracking/base.py", line 810, in _add_variable_with_custom_getter
    new_variable = getter(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variable_scope.py", line 1579, in get_variable
    return get_variable_scope().get_variable(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variable_scope.py", line 1322, in get_variable
    return var_store.get_variable(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variable_scope.py", line 578, in get_variable
    return _true_getter(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variable_scope.py", line 531, in _true_getter
    return self._get_single_variable(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variable_scope.py", line 952, in _get_single_variable
    v = variables.VariableV1(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 206, in _variable_v1_call
    return previous_getter(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variable_scope.py", line 2628, in default_variable_creator
    return variables.RefVariable(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 1656, in __init__
    self._init_from_args(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 1797, in _init_from_args
    initial_value = initial_value()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py", line 360, in __call__for_keras_init_v2
    return self._random_generator.random_uniform(shape, -limit, limit, dtype)
AttributeError: 'GlorotUniform' object has no attribute '_random_generator'
```

**Comment by rhdong** [comment]
> Hi @PWZER， thank you for your feedback; there's some limitations for using TFRA with TF. Please make sure that importing of TFRA should follow closely the importing of TensorFlow, so you can change the import sequence like this:
> 
> ```python
> import tensorflow as tf
> from tensorflow_recommenders_addons import dynamic_embedding as de
> 
> tf.compat.v1.disable_v2_behavior()  # remove this row is work
> ```

Anyone who met this issue, please refer to the method mentioned above, thank you very much~
