### ISSUE TITLE
keras model with de.keras.layers.SquashedEmbedding failed under tf.distribute.MirroredStrategy in TF2

### ISSUE THREAD

**Issue by cockroachzl** [tensorflow/recommenders-addons#238]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow version and how it was installed (source or binary): TensorFlow 2.8.0, installed with pip
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): built with source and TF2.8
- Python version: 3.8.8
- Is GPU used? (yes/no): yes, two A100 GPUs

**Describe the bug**

I could successfully run https://github.com/tensorflow/recommenders-addons/blob/master/demo/dynamic_embedding/movielens-1m-keras/movielens-1m-keras.py but the code failed when I want to train it with tf.distribute.MirroredStrategy

I am not sure if the behavior is expected or it is a bug. See the following code to reproduce this issue.

The primary error message is `ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'TrainableWrapperHandle:0' shape=(0, 32) dtype=float32, numpy=array([], shape=(0, 32), dtype=float32)>`, and I already passed the strategy to the SquashedEmbedding. 

```python
        self.user_embedding = de.keras.layers.SquashedEmbedding(
            user_embedding_size,
            initializer=embedding_initializer,
            name='user_embedding',
            distribute_strategy=distribute_strategy)
        self.movie_embedding = de.keras.layers.SquashedEmbedding(
            movie_embedding_size,
            initializer=embedding_initializer,
            name='movie_embedding',
            distribute_strategy=distribute_strategy)
```

I am not sure what the error message means, any help and explanation would be appreciated!

**Code to reproduce the issue**
```python

import os,sys

sys.version

import tensorflow as tf
import tensorflow_datasets as tfds

tf.version.VERSION

# +
# make TF not take all the GPU mem
gpus = tf.config.list_physical_devices('GPU')

# # Multi GPUs
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
print(f'gpus: {gpus}')
# -

from tensorflow_recommenders_addons import dynamic_embedding as de

from IPython.core.debugger import set_trace


class DualChannelsDeepModel(tf.keras.Model):

    def __init__(self,
               user_embedding_size=1,
               movie_embedding_size=1,
               embedding_initializer=None,
               is_training=True,
               distribute_strategy=None):

        if not is_training:
            de.enable_inference_mode()

        super(DualChannelsDeepModel, self).__init__()
        self.user_embedding_size = user_embedding_size
        self.movie_embedding_size = movie_embedding_size

        if embedding_initializer is None:
            embedding_initializer = tf.keras.initializers.Zeros()

        self.user_embedding = de.keras.layers.SquashedEmbedding(
            user_embedding_size,
            initializer=embedding_initializer,
            name='user_embedding',
            distribute_strategy=distribute_strategy)
        self.movie_embedding = de.keras.layers.SquashedEmbedding(
            movie_embedding_size,
            initializer=embedding_initializer,
            name='movie_embedding',
            distribute_strategy=distribute_strategy)

        self.dnn1 = tf.keras.layers.Dense(
            64,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.dnn2 = tf.keras.layers.Dense(
            16,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.dnn3 = tf.keras.layers.Dense(
            5,
            activation='softmax',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.bias_net = tf.keras.layers.Dense(
            5,
            activation='softmax',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))

    def call(self, features):
        user_id = tf.reshape(features['user_id'], (-1, 1))
        movie_id = tf.reshape(features['movie_id'], (-1, 1))
        user_latent = self.user_embedding(user_id)
        movie_latent = self.movie_embedding(movie_id)
        latent = tf.concat([user_latent, movie_latent], axis=1)

        x = self.dnn1(latent)
        x = self.dnn2(x)
        x = self.dnn3(x)

        bias = self.bias_net(latent)
        x = 0.2 * x + 0.8 * bias
        return x


def get_dataset(batch_size=1):
    dataset = tfds.load('movielens/1m-ratings', split='train')
#     dataset = tfds.load('movielens/100k-ratings', split='train')
    features = dataset.map(
      lambda x: {
          "movie_id": tf.strings.to_number(x["movie_id"], tf.int64),
          "user_id": tf.strings.to_number(x["user_id"], tf.int64),
      })
    ratings = dataset.map(
      lambda x: tf.one_hot(tf.cast(x['user_rating'] - 1, dtype=tf.int64), 5))
    dataset = dataset.zip((features, ratings))
    dataset = dataset.shuffle(4096, reshuffle_each_iteration=False)
    if batch_size > 1:
        dataset = dataset.batch(batch_size)

    return dataset


def dist_train():
    strategy = tf.distribute.MirroredStrategy()
    with strategy.scope():
        dataset = get_dataset(batch_size=32)
        model = DualChannelsDeepModel(32, 32,
                                    tf.keras.initializers.RandomNormal(0.0, 0.5), distribute_strategy=strategy)
        optimizer = tf.keras.optimizers.Adam(1E-3)
        optimizer = de.DynamicEmbeddingOptimizer(optimizer)

        auc = tf.keras.metrics.AUC(num_thresholds=1000)
        model.compile(optimizer=optimizer,
                      loss=tf.keras.losses.MeanSquaredError(),
                      metrics=[auc,],
#                       run_eagerly=True 
                     )
        model.fit(dataset, epochs=1, steps_per_epoch=2000)



dist_train()
```

**Other info / logs**

```python
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Error reported to Coordinator: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'TrainableWrapperHandle:0' shape=(0, 32) dtype=float32, numpy=array([], shape=(0, 32), dtype=float32)>
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/training/coordinator.py", line 293, in stop_on_exception
    yield
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_run.py", line 342, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step
    outputs = model.train_step(data)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 863, in train_step
    self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
    return self.apply_gradients(grads_and_vars, name=name)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 639, in apply_gradients
    self._create_all_weights(var_list)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 825, in _create_all_weights
    self._create_slots(var_list)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/adam.py", line 117, in _create_slots
    self.add_slot(var, 'm')
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py", line 197, in add_slot
    with strategy.extended.colocate_vars_with(var):
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2271, in colocate_vars_with
    self._validate_colocate_with_variable(colocate_with_variable)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 539, in _validate_colocate_with_variable
    distribute_utils.validate_colocate_distributed_variable(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_utils.py", line 238, in validate_colocate_distributed_variable
    raise ValueError(
ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'TrainableWrapperHandle:0' shape=(0, 32) dtype=float32, numpy=array([], shape=(0, 32), dtype=float32)>
INFO:tensorflow:Error reported to Coordinator: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'TrainableWrapperHandle:0' shape=(0, 32) dtype=float32, numpy=array([], shape=(0, 32), dtype=float32)>
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/training/coordinator.py", line 293, in stop_on_exception
    yield
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_run.py", line 342, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step
    outputs = model.train_step(data)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 863, in train_step
    self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
    return self.apply_gradients(grads_and_vars, name=name)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 639, in apply_gradients
    self._create_all_weights(var_list)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 825, in _create_all_weights
    self._create_slots(var_list)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/adam.py", line 117, in _create_slots
    self.add_slot(var, 'm')
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py", line 197, in add_slot
    with strategy.extended.colocate_vars_with(var):
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2271, in colocate_vars_with
    self._validate_colocate_with_variable(colocate_with_variable)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 539, in _validate_colocate_with_variable
    distribute_utils.validate_colocate_distributed_variable(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_utils.py", line 238, in validate_colocate_distributed_variable
    raise ValueError(
ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'TrainableWrapperHandle:0' shape=(0, 32) dtype=float32, numpy=array([], shape=(0, 32), dtype=float32)>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-3078b57388ec> in <module>
----> 1 dist_train()

<ipython-input-10-48715270d098> in dist_train()
     14 #                       run_eagerly=True
     15                      )
---> 16         model.fit(dataset, epochs=1, steps_per_epoch=2000)

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/six.py", line 703, in reraise
        raise value
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 863, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 639, in apply_gradients
        self._create_all_weights(var_list)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 825, in _create_all_weights
        self._create_slots(var_list)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/optimizer_v2/adam.py", line 117, in _create_slots
        self.add_slot(var, 'm')
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py", line 197, in add_slot
        with strategy.extended.colocate_vars_with(var):

    ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'TrainableWrapperHandle:0' shape=(0, 32) dtype=float32, numpy=array([], shape=(0, 32), dtype=float32)>
```

**Comment by Lifann** [comment]
Unfortunately, I haven't found out which is the best way to support mirrored strategy in TF2. But if you need to do synchronous training, here is a substitution:

```python
import os,sys
os.environ['CUDA_VISIBLE_DEVICES'] = '' # set to str(hvd.local_rank()) if need GPUs
import horovod.tensorflow as hvd
hvd.init()

sys.version

import tensorflow as tf
import tensorflow_datasets as tfds

tf.version.VERSION

from tensorflow_recommenders_addons import dynamic_embedding as de


class DualChannelsDeepModel(tf.keras.Model):

    def __init__(self,
               user_embedding_size=1,
               movie_embedding_size=1,
               embedding_initializer=None,
               is_training=True,
               distribute_strategy=None):

        if not is_training:
            de.enable_inference_mode()

        super(DualChannelsDeepModel, self).__init__()
        self.user_embedding_size = user_embedding_size
        self.movie_embedding_size = movie_embedding_size

        if embedding_initializer is None:
            embedding_initializer = tf.keras.initializers.Zeros()

        self.user_embedding = de.keras.layers.SquashedEmbedding(
            user_embedding_size,
            initializer=embedding_initializer,
            name='user_embedding',
            distribute_strategy=distribute_strategy)
        self.movie_embedding = de.keras.layers.SquashedEmbedding(
            movie_embedding_size,
            initializer=embedding_initializer,
            name='movie_embedding',
            distribute_strategy=distribute_strategy)

        self.dnn1 = tf.keras.layers.Dense(
            64,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.dnn2 = tf.keras.layers.Dense(
            16,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.dnn3 = tf.keras.layers.Dense(
            5,
            activation='softmax',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.bias_net = tf.keras.layers.Dense(
            5,
            activation='softmax',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))

    def call(self, features):
        user_id = tf.reshape(features['user_id'], (-1, 1))
        movie_id = tf.reshape(features['movie_id'], (-1, 1))
        user_latent = self.user_embedding(user_id)
        movie_latent = self.movie_embedding(movie_id)
        latent = tf.concat([user_latent, movie_latent], axis=1)

        x = self.dnn1(latent)
        x = self.dnn2(x)
        x = self.dnn3(x)

        bias = self.bias_net(latent)
        x = 0.2 * x + 0.8 * bias
        return x


def get_dataset(batch_size=1):
    dataset = tfds.load('movielens/1m-ratings', split='train')
    features = dataset.map(
      lambda x: {
          "movie_id": tf.strings.to_number(x["movie_id"], tf.int64),
          "user_id": tf.strings.to_number(x["user_id"], tf.int64),
      })
    ratings = dataset.map(
      lambda x: tf.one_hot(tf.cast(x['user_rating'] - 1, dtype=tf.int64), 5))
    dataset = dataset.zip((features, ratings))
    dataset = dataset.shuffle(4096, reshuffle_each_iteration=False)
    if batch_size > 1:
        dataset = dataset.batch(batch_size)

    return dataset


def dist_train():
    dataset = get_dataset(batch_size=32)
    dataset = dataset.shard(hvd.size(), hvd.rank())
    model = DualChannelsDeepModel(32, 32,
                                tf.keras.initializers.RandomNormal(0.0, 0.5))
    optimizer = tf.compat.v1.train.AdamOptimizer(1E-3)
    optimizer = de.DynamicEmbeddingOptimizer(optimizer, synchronous=True)

    auc = tf.keras.metrics.AUC(num_thresholds=1000)
    model.compile(optimizer=optimizer,
                  loss=tf.keras.losses.MeanSquaredError(),
                  metrics=[auc,],
                 )
    model.fit(dataset, epochs=1, steps_per_epoch=2000)



dist_train()
```

**Comment by MoFHeka** [comment]
Mirrored Strategy is now supported in TF2. But it has some performance problem, which cause by lacking of all-to-all communication operator.

**Comment by MoFHeka** [comment]
@cockroachzl This issue is solved for the time being, I will close this issue. Turn it back on if necessary.
