### ISSUE TITLE
[BUG] eager model savemodel, Abnormal : "ValueError: 'Tensor("checkpoint_key:0", shape=(), dtype=string)_table_restore' is not a valid scope name"

### ISSUE THREAD

**Issue by Mr-Nineteen** [tensorflow/recommenders-addons#44]
Scene recurrence:
**conda env：**

1. python version : 3
2. TF related installation library:
```
tensorflow                     2.4.1
tensorflow-datasets            4.2.0
tensorflow-estimator           2.4.0
tensorflow-metadata            0.29.0
tensorflow-recommenders-addons 0.1.0
```
3. test code:
```
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense

import tensorflow_datasets as tfds
import tensorflow_recommenders_addons as tfra
import tensorflow_recommenders_addons.dynamic_embedding as dynamic_embedding

ratings = tfds.load("movielens/100k-ratings", split="train")

ratings = ratings.map(lambda x: {
    "movie_id": tf.strings.to_number(x["movie_id"], tf.int64),
    "user_id": tf.strings.to_number(x["user_id"], tf.int64),
    "user_rating": x["user_rating"]
})

tf.random.set_seed(2021)
shuffled = ratings.shuffle(100_000, seed=2021, reshuffle_each_iteration=False)

dataset_train = shuffled.take(100_000).batch(256)


class NCFModel(tf.keras.Model):

    def __init__(self):
        super(NCFModel, self).__init__()
        self.embedding_size = 32
        self.d0 = Dense(
            256,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.d1 = Dense(
            64,
            activation='relu',
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.d2 = Dense(
            1,
            kernel_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1),
            bias_initializer=tf.keras.initializers.RandomNormal(0.0, 0.1))
        self.user_embeddings = tfra.dynamic_embedding.get_variable(
            name="user_dynamic_embeddings",
            dim=self.embedding_size,
            initializer=tf.keras.initializers.RandomNormal(-1, 1))
        self.movie_embeddings = tfra.dynamic_embedding.get_variable(
            name="moive_dynamic_embeddings",
            dim=self.embedding_size,
            initializer=tf.keras.initializers.RandomNormal(-1, 1))
        self.loss = tf.keras.losses.MeanSquaredError()

    def call(self, batch):
        movie_id = batch["movie_id"]
        user_id = batch["user_id"]
        rating = batch["user_rating"]

        user_id_val, user_id_idx = tf.unique(user_id)
        user_id_weights = tfra.dynamic_embedding.embedding_lookup(
            params=self.user_embeddings,
            ids=user_id_val,
            name="user-id-weights")
        user_id_weights = tf.gather(user_id_weights, user_id_idx)

        movie_id_val, movie_id_idx = tf.unique(movie_id)
        movie_id_weights = tfra.dynamic_embedding.embedding_lookup(
            params=self.movie_embeddings,
            ids=movie_id_val,
            name="movie-id-weights")
        movie_id_weights = tf.gather(movie_id_weights, movie_id_idx)

        embeddings = tf.concat([user_id_weights, movie_id_weights], axis=1)
        dnn = self.d0(embeddings)
        dnn = self.d1(dnn)
        dnn = self.d2(dnn)
        out = tf.reshape(dnn, shape=[-1])
        loss = self.loss(rating, out)
        return loss


model = NCFModel()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
optimizer = tfra.dynamic_embedding.DynamicEmbeddingOptimizer(optimizer)


def train(epoch=1):
    for i in range(epoch):
        total_loss = np.array([])
        for (_, batch) in enumerate(dataset_train):
            with tf.GradientTape() as tape:
                loss = model(batch)
                total_loss = np.append(total_loss, loss)
            grads = tape.gradient(loss, model.trainable_variables)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))
        print("epoch:", i, "mean_squared_error:", np.mean(total_loss))


if __name__ == "__main__":
    train(1)

    model.save("models/de")

```
4. Error message:
```
Traceback (most recent call last):
  File "/Users/dxwang/repo/pycharm-repo/tensorflow-2.0-demo/com/opensource/demo/tfra/de-demo.py", line 100, in <module>
    model.save("models/de")
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    signatures, options, save_traces)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    save_lib.save(model, filepath, signatures, options)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1147, in _build_meta_graph_impl
    _ = _SaveableView(checkpoint_graph_view, options)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 195, in __init__
    self._add_saveable_objects())
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 254, in _add_saveable_objects
    saveable_map = saveable_object_util.trace_save_restore_functions(node)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 386, in trace_save_restore_functions
    saveable_factory, object_to_save)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 442, in _trace_save_and_restore_function
    concrete_restore_fn = restore_fn.get_concrete_function()
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py:439 restore_fn  *
        saveable.restore(restored_tensors, restored_shapes=None)
    /Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py:305 restore  *
        with ops.name_scope("%s_table_restore" % self.table_name):
    /Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:6507 __enter__
        return self._name_scope.__enter__()
    /Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:4246 name_scope
        raise ValueError("'%s' is not a valid scope name" % name)

    ValueError: 'Tensor("checkpoint_key:0", shape=(), dtype=string)_table_restore' is not a valid scope name

```

**Comment by MsDidin** [comment]
There is also error message when save model after the fix Support Keras APIs and fix save-restore issue in TF2 #119:

Traceback (most recent call last):
  File "keras_tfra.py", line 96, in <module>
    model.save("dynamic_embedding/1")
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    signatures, options, save_traces)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    save_lib.save(model, filepath, signatures, options)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1133, in _build_meta_graph_impl
    checkpoint_graph_view)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 151, in list_functions
    self._serialization_cache)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2613, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3087, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 94, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 79, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 51, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 205, in default_save_signature
    fn.get_concrete_function()
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 135, in _wrapped_model
    outputs = model(inputs, training=False)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)
  File "keras_tfra.py", line 55, in call
    user_id_val, user_id_idx = np.unique(user_id, return_inverse=True)
  File "<__array_function__ internals>", line 6, in unique
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 259, in unique
    ar = np.asanyarray(ar)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 855, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (user_id:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by Lifann** [comment]
> There is also error message when save model after the fix Support Keras APIs and fix save-restore issue in TF2 #119:
> 
> Traceback (most recent call last):
> File "keras_tfra.py", line 96, in
> model.save("dynamic_embedding/1")
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
> signatures, options, save_traces)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
> signatures, options, save_traces)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
> save_lib.save(model, filepath, signatures, options)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1033, in save
> obj, signatures, options, meta_graph_def)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
> return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1133, in _build_meta_graph_impl
> checkpoint_graph_view)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
> functions = saveable_view.list_functions(saveable_view.root)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 151, in list_functions
> self._serialization_cache)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2613, in _list_functions_for_serialization
> Model, self)._list_functions_for_serialization(serialization_cache)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3087, in _list_functions_for_serialization
> .list_functions_for_serialization(serialization_cache))
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 94, in list_functions_for_serialization
> fns = self.functions_to_serialize(serialization_cache)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 79, in functions_to_serialize
> serialization_cache).functions_to_serialize)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
> serialization_cache)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 51, in _get_serialized_attributes_internal
> default_signature = save_impl.default_save_signature(self.obj)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 205, in default_save_signature
> fn.get_concrete_function()
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
> concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
> self._initialize(args, kwargs, add_initializers_to=initializers)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
> *args, **kwds))
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
> graph_function, _ = self._maybe_define_function(args, kwargs)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
> graph_function = self._create_graph_function(args, kwargs)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
> capture_by_value=self._capture_by_value),
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
> func_outputs = python_func(*func_args, **func_kwargs)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
> out = weak_wrapped_fn().**wrapped**(*args, **kwds)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 135, in _wrapped_model
> outputs = model(inputs, training=False)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in **call**
> outputs = call_fn(inputs, *args, **kwargs)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
> return func(*args, **kwargs)
> File "keras_tfra.py", line 55, in call
> user_id_val, user_id_idx = np.unique(user_id, return_inverse=True)
> File "<**array_function** internals>", line 6, in unique
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 259, in unique
> ar = np.asanyarray(ar)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
> return array(a, dtype, copy=False, order=order, subok=True)
> File "/Users/ding/opt/anaconda3/envs/tfra-env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 855, in **array**
> " a NumPy call, which is not supported".format(self.name))
> NotImplementedError: Cannot convert a symbolic Tensor (user_id:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Hi, @MsDidin . Could you please give a code snippet to reproduce this issue?

Currently, there still are some obstacles to eager runtime. And we are working on it.

Maybe [eager demo](https://github.com/tensorflow/recommenders-addons/blob/master/demo/dynamic_embedding/amazon-us-reviews-digital-video-games/main.py#L59-L64) will offer some help. Feel free to reply.
