### ISSUE TITLE
Build GPU operation got bzl error.

### ISSUE THREAD

**Issue by Lifann** [tensorflow/recommenders-addons#52]
I'm trying to build a GPU operation for TFRA. [here](https://github.com/Lifann/recommenders-addons/blob/Lifann/support-sparse-segment-sum-ops-on-gpu/tensorflow_recommenders_addons/dynamic_embedding/core/BUILD#L17-L29)

And use compilation procedure as follows:
```
# set env options:
CUDNN_INSTALL_PATH="/data/dev/cuda"  TF_NEED_CUDA=1 python configure.py
```

I get the correct environment settings:
```
Configuring TensorFlow Recommenders-Addons to be built from source...
> Building GPU & CPU ops

Build configurations successfully written to .bazelrc :

build --action_env TF_HEADER_DIR="/data/env/py3/lib64/python3.6/site-packages/tensorflow/include"
build --action_env TF_SHARED_LIBRARY_DIR="/data/env/py3/lib64/python3.6/site-packages/tensorflow"
build --action_env TF_SHARED_LIBRARY_NAME="libtensorflow_framework.so.2"
build --action_env TF_CXX11_ABI_FLAG="0"
build --spawn_strategy=standalone
build --strategy=Genrule=standalone
build -c opt
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env CUDNN_INSTALL_PATH="/data/dev/cuda"
build --action_env TF_CUDA_VERSION="10.1"
build --action_env TF_CUDNN_VERSION="7"
test --config=cuda
build --config=cuda
build:cuda --define=using_cuda=true --define=using_cuda_nvcc=true
build:cuda --crosstool_top=@local_config_cuda//crosstool:toolchain
```

## But when I run the building process: 
```
# start building:
bazel build  //tensorflow_recommenders_addons/dynamic_embedding/core:_segment_reduction_ops.so
```

## I got errors: 
```
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  /data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl:1083:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1081
                _create_local_cuda_repository(<1 more arguments>)
        File "/data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1017, in _create_local_cuda_repository
                one_line.split(":")[1]
index out of range (index is 1, but sequence has 1 elements)
ERROR: Skipping '//tensorflow_recommenders_addons/dynamic_embedding/core:_segment_reduction_ops.so': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1081
                _create_local_cuda_repository(<1 more arguments>)
        File "/data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1017, in _create_local_cuda_repository
                one_line.split(":")[1]
index out of range (index is 1, but sequence has 1 elements)
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1081
                _create_local_cuda_repository(<1 more arguments>)
        File "/data/dev/recommenders-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1017, in _create_local_cuda_repository
                one_line.split(":")[1]
index out of range (index is 1, but sequence has 1 elements)
INFO: Elapsed time: 0.284s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow_recommenders_addons/dynamic_embedding/core
```

-----
It seems there some BUG here for GPU building process.

The bazel toolchain seems to be a large module for me. Are there any suggestions to solve this problem?

**Comment by Lifann** [comment]
The problem is solved by PR [here](https://github.com/tensorflow/recommenders-addons/pull/53).
